bmw-tech/dart_apitool

.github/workflows/ci.yml
=> New minimum pana score

.github/workflows/check_version.yml, .github/workflows/ci.yml
uses dart_apitool provided workflow
=> adds "check semver" step

CHANGELOG.md, lib/src/cli/commands/diff_command.dart, pubspec.yaml
=> better pre-release handling

CHANGELOG.md, lib/src/analyze/package_api_analyzer.dart, lib/src/analyze/package_api_analyzer.freezed.dart, lib/src/cli/commands/diff_command.dart, lib/src/diff/package_api_differ.dart, lib/src/model/class_declaration.dart, lib/src/model/class_declaration.freezed.dart, lib/src/model/declaration.dart, lib/src/model/executable_declaration.dart, lib/src/model/executable_declaration.freezed.dart, lib/src/model/field_declaration.dart, lib/src/model/field_declaration.freezed.dart, lib/src/model/internal/internal_class_declaration.dart, lib/src/model/internal/internal_declaration.dart, lib/src/model/internal/internal_executable_declaration.dart, lib/src/model/internal/internal_field_declaration.dart, lib/src/storage/v1/class_declaration_storage_v1.dart, lib/src/storage/v1/class_declaration_storage_v1.freezed.dart, lib/src/storage/v1/class_declaration_storage_v1.g.dart, lib/src/storage/v1/executable_declaration_storage_v1.dart, lib/src/storage/v1/executable_declaration_storage_v1.freezed.dart, lib/src/storage/v1/executable_declaration_storage_v1.g.dart, lib/src/storage/v1/field_declaration_storage_v1.dart, lib/src/storage/v1/field_declaration_storage_v1.freezed.dart, lib/src/storage/v1/field_declaration_storage_v1.g.dart, lib/src/tooling/dart_interaction.dart
This PR adds entry points to the list of things that belong to a public API.
An entry point is a publicly available import destination that imports the element.
It is part of the public API as changing the entry points can lead to changes in the client code
=> Entry Points analysis and diffing

lib/src/analyze/package_api_analyzer.dart, lib/src/model/internal/internal_class_declaration.dart, lib/src/model/internal/internal_declaration.dart, lib/src/model/internal/internal_executable_declaration.dart, lib/src/model/internal/internal_field_declaration.dart
much easier aggregating collected findings.
The immutable, public model gets then created from the internal model elements
=> refactor internal model to be mutable

lib/src/analyze/api_relevant_elements_collector.dart
extends implicit type usage tracking to any kind of Element (in practice this is InterfaceType and TypeAlias)
=> Improve implicit type usage analysis

test/integration_tests/analyze/bloc_test.dart, test/integration_tests/analyze/device_info_plus_test.dart, test/integration_tests/analyze/mockito_test.dart, test/integration_tests/diff/device_info_plus_platform_interface_test.dart, test/integration_tests/diff/share_plus_test.dart, test/integration_tests/diff/xterm_test.dart, test/integration_tests/helper/integration_test_helper.dart
by introducing a helper class to retrieve pub packages
=> improves integration tests

.github/workflows/ci.yml
This PR adds a code test coverage test step to CI
=> adds coverage test step

.fvm/fvm_config.json, CHANGELOG.md
prepares Changelog entry for 0.10.1
Upgrades Flutter to 3.3.10
=> [Chore] prepare Changelog & upgrade Flutter

CHANGELOG.md, README.md, lib/src/cli/commands/command_mixin.dart, lib/src/cli/commands/diff_command.dart, lib/src/cli/commands/extract_command.dart, lib/src/tooling/dart_interaction.dart, lib/src/tooling/pub_interaction.dart, lib/src/utils/process_utils.dart, lib/src/utils/stdout_session.dart, lib/src/utils/utils.dart
adds subprocess "window" to temporary see the subprocess output
also adds `--remove-example` flag as some packages on pub have broken example packages and those are not interesting for the analysis but break `pub get`
fixes #101 
https://user-images.githubusercontent.com/6693130/218150039-a33c69dd-b291-4527-a1a4-0f345685a452.mp4
=> Show subprocess output

.fvm/fvm_config.json, .github/workflows/ci.yml, CHANGELOG.md, README.md, lib/src/cli/commands/diff_command.dart, pubspec.yaml
Adapts all references to the old repository location to the new one.
Increase Flutter version to latest stable.
=> (chore) move to bmw-tech

.vscode/settings.json, CHANGELOG.md, lib/src/analyze/api_relevant_elements_collector.dart, lib/src/diff/package_api_differ.dart
This PR fixes the detection of "Required Interfaces" for property and field usage
=> fix required interface detection on properties and fields

pubspec.yaml
=> Release v0.14.0

lib/src/storage/v3/interface_declaration_storage_v3.dart, readme/change_codes.md, test/package_api_storage_test.dart
- Fixed isSealed assignment in InterfaceDeclarationStorageV3.
- (Typo) Changed CI10 reference to CI11 in change_codes.md
=> fix: Correctly export isSealed

pubspec.yaml
This PR sets the next version after v0.14.1 has been released
=> Release v0.14.1

.fvm/fvm_config.json, lib/src/model/internal/internal_declaration_utils.dart, lib/src/model/internal/internal_interface_declaration.dart, pubspec.yaml, test/integration_tests/cli/diff_command_test.dart, test/integration_tests/cli/extract_command_test.dart, test/integration_tests/helper/integration_test_helper.dart
Grouping super types with the same name (for now) as we currently don't dig too deep into the type hierarchy
Fixes #153
=> Fixing grpc diff crash

pubspec.yaml
This PR contains the 0.16.0 release changes
=> Release 0.16.0

pubspec.yaml
Hotfix release to fix an issue with pubspec_overrides.yaml in packages that are referenced from pub
=> Release 0.16.1

pubspec.yaml
=> Release 0.16.2

CHANGELOG.md, lib/src/analyze/package_api_analyzer.freezed.dart, lib/src/model/executable_declaration.freezed.dart, lib/src/model/field_declaration.freezed.dart, lib/src/model/interface_declaration.freezed.dart, lib/src/model/package_api.freezed.dart, lib/src/model/package_dependency.freezed.dart, lib/src/model/platform_constraints.freezed.dart, lib/src/model/type_alias_declaration.freezed.dart, lib/src/model/type_hierarchy.freezed.dart, lib/src/storage/v3/executable_declaration_storage_v3.freezed.dart, lib/src/storage/v3/field_declaration_storage_v3.freezed.dart, lib/src/storage/v3/interface_declaration_storage_v3.freezed.dart, lib/src/storage/v3/package_api_storage_v3.freezed.dart, lib/src/storage/v3/package_dependency_storage_v3.freezed.dart, lib/src/storage/v3/platform_constraints_storage_v3.freezed.dart, lib/src/storage/v3/type_alias_declaration_storage_v3.freezed.dart, lib/src/tooling/pub_interaction.dart
Search downloaded packages in entire .pub-cache hosted directory in case path namining changes.
=> Search downloaded packages in entire .pub-cache hosted directory

lib/src/analyze/package_api_analyzer.freezed.dart, lib/src/model/executable_declaration.freezed.dart, lib/src/model/field_declaration.freezed.dart, lib/src/model/interface_declaration.freezed.dart, lib/src/model/package_api.freezed.dart, lib/src/model/package_dependency.freezed.dart, lib/src/model/platform_constraints.freezed.dart, lib/src/model/type_alias_declaration.freezed.dart, lib/src/model/type_hierarchy.freezed.dart, lib/src/storage/v3/executable_declaration_storage_v3.freezed.dart, lib/src/storage/v3/field_declaration_storage_v3.freezed.dart, lib/src/storage/v3/interface_declaration_storage_v3.freezed.dart, lib/src/storage/v3/package_api_storage_v3.freezed.dart, lib/src/storage/v3/package_dependency_storage_v3.freezed.dart, lib/src/storage/v3/platform_constraints_storage_v3.freezed.dart, lib/src/storage/v3/type_alias_declaration_storage_v3.freezed.dart
This PR fixes the build_runner output on main branch (There has been a freezed release in the meantime)
=> fix build_runner on main

pubspec.yaml
=> Release 0.18.0

pubspec.yaml
=> Release 0.19.0

.gitignore, CHANGELOG.md, pubspec.yaml
This PR is setting the analyzer's lower boundary to 5.6, in order to avoid the 'withNullability' as a required param.
=> set minimum boundary of analyzer package

pubspec.yaml
=> Release 0.20.2

CHANGELOG.md, pubspec.yaml, scripts/release_util/lib/src/release_command.dart
=> Release 0.23.0
