bmw-tech/dart_apitool

lib/src/cli/commands/command_mixin.dart
This PR introduces a differentiation between dart and flutter projects when the project gets prepared.
It tries to find flutter based on the path the executing dart executable has
=> Differentiate between Dart and Flutter projects

CHANGELOG.md, lib/src/analyze/package_api_analyzer.dart
If a package has root elements (without class context) the merge classes functionality crashes.
This PR fixes that behavior
=> Bugfix: merge classes and root elements

.github/workflows/ci.yml, pubspec.yaml
This PR adds another GH action step to use the dart-apitool from the current branch additionally to the latest released one
=> use latest dart-apitool (from current branch) additionally in GH workflow

.fvm/fvm_config.json, CHANGELOG.md, lib/src/analyze/package_api_analyzer.dart, lib/src/model/internal/internal_executable_declaration.dart, lib/src/model/internal/internal_field_declaration.dart, lib/src/model/internal/internal_interface_declaration.dart, lib/src/model/internal/internal_type_alias_declaration.dart, pubspec.yaml
This PR changes the analyzer behavior so that elements that don't have a collected parent element get ignored (instead of adding them to root wich can cause naming collisions).
Fixes https://github.com/devmil/dart_apitool/issues/69
=> ignore unmatched elements

CHANGELOG.md, lib/src/analyze/api_relevant_elements_collector.dart, lib/src/analyze/package_api_analyzer.dart, lib/src/diff/package_api_differ.dart, lib/src/model/interface_declaration.dart, lib/src/model/interface_declaration.freezed.dart, lib/src/model/internal/internal_interface_declaration.dart, lib/src/storage/v3/interface_declaration_storage_v3.dart, lib/src/storage/v3/interface_declaration_storage_v3.freezed.dart, lib/src/storage/v3/interface_declaration_storage_v3.g.dart, pubspec.yaml, test/integration_tests/diff/sqflite_common_test.dart, test/package_api_differ_test_data.dart, test/package_api_storage_test.dart
This PR adds the detection of required interfaces.
Required interfaces are interfaces (abstract classes) that might be intended to be implemented by the user of the API.
If those interfaces are changed (even if only stuff got added) then this changes is breaking.
The Analyzer part of dart_apitool considers interfaces required if they are abstract and used as an executable parameter or writable field.
Fixes https://github.com/devmil/dart_apitool/issues/70
=> Abstract required interface change breaks

CHANGELOG.md, lib/src/analyze/api_relevant_elements_collector.dart, lib/src/analyze/package_api_analyzer.dart, lib/src/diff/package_api_differ.dart, lib/src/model/internal/internal_declaration_utils.dart, lib/src/model/internal/internal_executable_declaration.dart, lib/src/model/internal/internal_field_declaration.dart, lib/src/model/internal/internal_interface_declaration.dart, lib/src/model/internal/internal_type_alias_declaration.dart, test/test_packages/experimental_diff/package_a_with_experimental/lib/duplicates/class_a.dart, test/test_packages/experimental_diff/package_a_with_experimental/lib/package_a_duplicates.dart, test/test_packages/experimental_diff/package_a_with_experimental/pubspec.yaml, test/test_packages/experimental_diff/package_a_without_experimental/lib/duplicates/class_a.dart, test/test_packages/experimental_diff/package_a_without_experimental/lib/package_a_duplicates.dart, test/test_packages/experimental_diff/package_a_without_experimental/pubspec.yaml
- relative path comparison is now used for all types (interface, executable, field) but only on top-level
- the relative path is now calculated based on the root path that is passed in instead of some wild name-guessing on the file path
=> Relative path usage cleanup

CHANGELOG.md, lib/src/cli/commands/diff_command.dart, lib/src/diff/diff.dart, lib/src/diff/version_check_mode.dart, pubspec.yaml, test/integration_tests/cli/diff_command_test.dart
This PR fixes the version check behavior if there are no changes (#92).
It also introduces a more fine granular selection of what part of the version to check (#91)
=> Fix version check on no changes and introduce version check mode

CHANGELOG.md, lib/src/cli/commands/command_mixin.dart, test/integration_tests/cli/diff_command_test.dart, test/integration_tests/cli/extract_command_test.dart, test/test_packages/nested_path_references/package_a/.gitignore, test/test_packages/nested_path_references/package_a/CHANGELOG.md, test/test_packages/nested_path_references/package_a/README.md, test/test_packages/nested_path_references/package_a/analysis_options.yaml, test/test_packages/nested_path_references/package_a/lib/package_a.dart, test/test_packages/nested_path_references/package_a/lib/types/class_a.dart, test/test_packages/nested_path_references/package_a/package_b/.gitignore, test/test_packages/nested_path_references/package_a/package_b/CHANGELOG.md, test/test_packages/nested_path_references/package_a/package_b/README.md, test/test_packages/nested_path_references/package_a/package_b/analysis_options.yaml, test/test_packages/nested_path_references/package_a/package_b/lib/package_b.dart, test/test_packages/nested_path_references/package_a/package_b/lib/types/class_b.dart, test/test_packages/nested_path_references/package_a/package_b/package_c/.gitignore, test/test_packages/nested_path_references/package_a/package_b/package_c/CHANGELOG.md, test/test_packages/nested_path_references/package_a/package_b/package_c/README.md, test/test_packages/nested_path_references/package_a/package_b/package_c/analysis_options.yaml, test/test_packages/nested_path_references/package_a/package_b/package_c/lib/package_c.dart, test/test_packages/nested_path_references/package_a/package_b/package_c/lib/types/class_c.dart, test/test_packages/nested_path_references/package_a/package_b/package_c/pubspec.yaml, test/test_packages/nested_path_references/package_a/package_b/pubspec.yaml, test/test_packages/nested_path_references/package_a/pubspec.yaml
This PR introduces a fix for an issue with nested path dependencies.
It filters all paths that already have a parent path in the list from the list of directories to copy.
Also introduces bigger timeouts for the CLI integration tests (solves #95)
=> Bugfix: handle nested projects with path dependencies

.fvm/fvm_config.json, CHANGELOG.md, lib/src/analyze/package_api_analyzer.dart
This PR fixes local package references (they became absolute instead of relative)
also: increase Flutter version to 3.7.3
fixes #106
=> fix local package refs

CHANGELOG.md, lib/src/cli/commands/diff_command.dart, lib/src/diff/api_change_type.dart, lib/src/diff/package_api_differ.dart, pubspec.yaml, readme/change_codes.md, test/integration_tests/diff/cloud_firestore_test.dart, test/integration_tests/diff/flutter_blue_test.dart, test/integration_tests/diff/xterm_test.dart, test/package_api_differ_test.dart
Changes in dependencies that are compatible only lead to an expected patch version increase.
The same goes for dependency removals.
fixes #105
=> improve dependency diffing

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, bin/main.dart
This PR copies the contribution infrastructure from widget_driver:
- issue templates
- pull request template
- code of conduct
- contribution guide
- code owners
=> add contribution infrastructure

CHANGELOG.md, lib/src/tooling/dart_interaction.dart, lib/src/utils/process_utils.dart
This PR changes the way resolving issues of the Flutter executable are handled.
Instead of throwing an exception now this issue is logged and the system wide Flutter executable is used to execute `pub get`
=> Improve flutter resolve handling

CHANGELOG.md, README.md, lib/src/cli/commands/diff_command.dart, lib/src/cli/commands/version_check.dart, pubspec.yaml, test/unit_tests/cli/commands/version_check_test.dart
This PR fixes pre-release handling in dart_apitool.
Now also pre-release tags of the old version are taken into account and loosen the requirements for the new version.
**Breaking change**: the default for `--ignore-prerelease` is now `on`.
Fixes #117
=> fix!: Improves handling of pre-release versions

CHANGELOG.md, lib/src/analyze/api_relevant_elements_collector.dart, test/integration_tests/diff/enum_ctor_and_tostring_test.dart, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/.gitignore, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/CHANGELOG.md, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/README.md, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/analysis_options.yaml, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/lib/package_a.dart, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/lib/src/class_a.dart, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/lib/src/enum_a.dart, test/test_packages/enum_and_tostring/package_a_with_enum_ctor_and_tostring/pubspec.yaml, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/.gitignore, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/CHANGELOG.md, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/README.md, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/analysis_options.yaml, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/lib/package_a.dart, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/lib/src/class_a.dart, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/lib/src/enum_a.dart, test/test_packages/enum_and_tostring/package_a_without_enum_ctor_and_tostring/pubspec.yaml
This PR filters enum constructors and `toString()` + `hashCode` from the analyzed public API as those have no relevance regarding public API changes.
Fixes #126 
Fixes #125
=> fix: Enum constructors and overrides of object defined elements should not be public api

test/integration_tests/diff/test_package_experimental_test.dart, test/integration_tests/diff/test_package_sealed_test.dart
This PR makes some unit test cleanup as suggested in #132
=> chore: replaces apiChange length check + any expectation with containsOnce + predicate

.fvm/fvm_config.json, CHANGELOG.md, README.md, lib/api_tool.dart, lib/src/analyze/api_relevant_elements_collector.dart, lib/src/analyze/package_api_analyzer.dart, lib/src/cli/commands/command_mixin.dart, lib/src/cli/commands/diff_command.dart, lib/src/cli/commands/extract_command.dart, lib/src/model/interface_declaration.dart, lib/src/model/interface_declaration.freezed.dart, lib/src/model/internal/internal_interface_declaration.dart, lib/src/model/model.dart, lib/src/model/package_api.dart, lib/src/model/package_api_semantics.dart, lib/src/model/type_usage.dart, lib/src/storage/v3/package_api_storage_v3.g.dart, test/integration_tests/cli/extract_command_test.dart, test/integration_tests/diff/test_package_experimental_test.dart, test/integration_tests/diff/test_package_sealed_test.dart, test/package_api_differ_test_data.dart, test/package_api_storage_test.dart, test/test_packages/missing_export/package_a/.gitignore, test/test_packages/missing_export/package_a/CHANGELOG.md, test/test_packages/missing_export/package_a/README.md, test/test_packages/missing_export/package_a/analysis_options.yaml, test/test_packages/missing_export/package_a/lib/package_a.dart, test/test_packages/missing_export/package_a/lib/types/class_a.dart, test/test_packages/missing_export/package_a/lib/types/class_b.dart, test/test_packages/missing_export/package_a/pubspec.yaml
This PR adds a first check for interfaces that are part of the public API but are not exported.
This is done by gathering a bit more information about the usage context of a type (and along the way replacing `isRequired`) to then strip out all interfaces that are not used as input or output and are not reachable (have no entry points).
All interfaces that are left afterwards and have no entry points are potentially problematic as they are used as input or output but are not addressable from a consumer of the package.
Also introduces ` --[no-]set-exit-on-missing-export` flag for the extract command that fails the export if a missing export is detected.
This is the compromise on having this check available without introducing an `analyze` command with exactly one check.  
If we get more …
=> add unexported interfaces check

CHANGELOG.md, lib/src/cli/commands/command_mixin.dart, test/test_packages/path_references/cluster_a/package_b/pubspec.yaml
This PR fixes the functionality to collect path dependencies to also look at dev dependencies.
=> respect dev dependencies when looking for path dependencies

CHANGELOG.md, README.md, lib/src/cli/commands/diff_command.dart, lib/src/diff/dependency_check_mode.dart, lib/src/diff/package_api_differ.dart, lib/src/diff/package_api_differ_options.dart, pubspec.yaml, test/integration_tests/diff/flutter_blue_test.dart, test/integration_tests/diff/xterm_test.dart
This PR removes the effect of `--dependency-check-mode` as this is no longer needed (see #144)
Solves issue #144
=> remove effect of `--dependency-check-mode`

CHANGELOG.md, lib/src/cli/commands/command_mixin.dart
If a package bundles a pubspec_overrides.yaml (e.g. because it lives in a multi-package repo) that overrides are most probably no longer valid for the package in isolation.
This is no problem if a package gets referenced as the overrides only work locally.
In dart_apitool's case this is a problem as it wants to run pub get on a local copy of that package and therefore needs to clean up pubspec_overrides if they exist.
=> fix: removes pubspec_overrides.yaml from a package downloaded from pub

.fvm/fvm_config.json, CHANGELOG.md, README.md, bin/main.dart, lib/src/cli/commands/diff_command.dart, lib/src/diff/api_change_code.dart, lib/src/diff/report/console_diff_reporter.dart, lib/src/diff/report/diff_reporter.dart, lib/src/diff/report/json_diff_reporter.dart, lib/src/diff/report/markdown_diff_reporter.dart, lib/src/diff/report/report_format.dart, lib/src/utils/declaration_utils.dart, lib/src/utils/utils.dart, lib/src/utils/version_utils.dart, readme/change_codes.md, test/integration_tests/cli/diff_command_test.dart, test/unit_tests/diff/report/console_diff_reporter_test.dart
This PR aims to implement the feature described in issue #137, which allows the creation of a Markdown report containing the differences between the two compared APIs.
Currently, it displays the API differences in the Markdown report but does not include any semver warnings or errors. This omission was intentional because it wasn't clear if it was a requirement. However, we can add this functionality if needed.
Additionally, this PR lays the foundation for future report formats. It introduces an abstraction layer to the diff command, which now supports the following report formats:
- CLI (The default format, unchanged from before)
- Markdown
- JSON (Might need to be checked if we want to keep that implementation because  of #150)
When you run the diff command as you normally would, the …
=> Add support for multiple diff report formats

test/integration_tests/cli/extract_command_test.dart
This PR adds an regression integration test for the recently fixed issue of relative path dependencies leading to unresolvable types.
=> chore: adds an integration test for the recent relative path issue

CHANGELOG.md, lib/src/analyze/package_api_analyzer.dart, lib/src/analyze/package_api_analyzer.freezed.dart, lib/src/cli/commands/command_mixin.dart, lib/src/model/executable_declaration.freezed.dart, lib/src/model/field_declaration.freezed.dart, lib/src/model/interface_declaration.freezed.dart, lib/src/model/package_api.freezed.dart, lib/src/model/package_dependency.freezed.dart, lib/src/model/platform_constraints.freezed.dart, lib/src/model/type_alias_declaration.freezed.dart, lib/src/model/type_hierarchy.dart, lib/src/model/type_hierarchy.freezed.dart, lib/src/storage/v3/executable_declaration_storage_v3.freezed.dart, lib/src/storage/v3/executable_declaration_storage_v3.g.dart, lib/src/storage/v3/field_declaration_storage_v3.freezed.dart, lib/src/storage/v3/field_declaration_storage_v3.g.dart, lib/src/storage/v3/interface_declaration_storage_v3.freezed.dart, lib/src/storage/v3/interface_declaration_storage_v3.g.dart, lib/src/storage/v3/package_api_storage_v3.freezed.dart, lib/src/storage/v3/package_api_storage_v3.g.dart, lib/src/storage/v3/package_dependency_storage_v3.freezed.dart, lib/src/storage/v3/package_dependency_storage_v3.g.dart, lib/src/storage/v3/platform_constraints_storage_v3.freezed.dart, lib/src/storage/v3/platform_constraints_storage_v3.g.dart, lib/src/storage/v3/type_alias_declaration_storage_v3.freezed.dart, lib/src/storage/v3/type_alias_declaration_storage_v3.g.dart, test/integration_tests/cli/extract_command_test.dart, test/test_packages/path_references/cluster_a/package_a/lib/types/class_a.dart, test/test_packages/path_references/cluster_a/package_a/lib/types/mixin_a.dart
The logic that is adapting relative paths in the package_config.json also adapts the relative path to the main package (../) breaking any imports that use the package ref even inside the package.
This PR fixes that by omitting that directory from the adaption logic
=> fix: fixes local package refs

.fvm/fvm_config.json, CHANGELOG.md, pubspec.yaml, test/integration_tests/diff/test_package_records_test.dart, test/test_packages/records/package_a_with_changed_record/.gitignore, test/test_packages/records/package_a_with_changed_record/CHANGELOG.md, test/test_packages/records/package_a_with_changed_record/README.md, test/test_packages/records/package_a_with_changed_record/analysis_options.yaml, test/test_packages/records/package_a_with_changed_record/lib/package_a.dart, test/test_packages/records/package_a_with_changed_record/lib/src/class_a.dart, test/test_packages/records/package_a_with_changed_record/pubspec.yaml, test/test_packages/records/package_a_with_record/.gitignore, test/test_packages/records/package_a_with_record/CHANGELOG.md, test/test_packages/records/package_a_with_record/README.md, test/test_packages/records/package_a_with_record/analysis_options.yaml, test/test_packages/records/package_a_with_record/lib/package_a.dart, test/test_packages/records/package_a_with_record/lib/src/class_a.dart, test/test_packages/records/package_a_with_record/pubspec.yaml
This PR does:
- bump the used Flutter version to 3.16.4
- upgrades dependencies
- sets the minimum Dart SDK to 3.0.0
- adds a Unit test for Record structure change detection
=> Flutter upgrade and Record support

CHANGELOG.md, lib/src/cli/commands/diff_command.dart, lib/src/cli/commands/version_check.dart, lib/src/diff/report/console_diff_reporter.dart, lib/src/diff/report/diff_reporter.dart, lib/src/diff/report/json_diff_reporter.dart, lib/src/diff/report/markdown_diff_reporter.dart, lib/src/tooling/pub_interaction.dart, test/unit_tests/cli/commands/version_check_test.dart, test/unit_tests/diff/report/console_diff_reporter_test.dart
For our [health.yaml](https://github.com/dart-lang/ecosystem/blob/main/.github/workflows/health.yaml) workflow, it would be ideal if the version checking would also be part of the JSON report.
=> Add version check to reported output

.fvm/fvm_config.json, CHANGELOG.md, lib/src/model/type_hierarchy.dart, test/integration_tests/diff/http2_test.dart, test/integration_tests/helper/integration_test_helper.dart
This PR fixes the change compatibility handling for `dynamic` and `Object?` so that changing the type of a parameter from `dynamic` to `Object?` is no longer breaking.
This fixes #172
=> Treat dynamic and object equivalent for inflowing usages

CHANGELOG.md, README.md, lib/src/cli/commands/diff_command.dart, lib/src/diff/package_api_differ.dart, readme/change_codes.md
Changing the SDK version can't break existing consumer code as pub would not consider the new package that has a non-fitting SDK version boundary. 
That way the existing code would continue to use the older version that still has a fitting SDK version. 
A package owner might still consider introducing a major version bump in that case, that's why this option is still there but off by default
Fixes #183
=> changes the default for checking the SDK version and treating it as a breaking change to `off`

CHANGELOG.md, lib/src/cli/commands/command_mixin.dart, lib/src/cli/package_ref.dart, lib/src/diff/report/json_diff_reporter.dart, lib/src/tooling/pub_interaction.dart, pubspec.yaml, test/integration_tests/cli/diff_command_test.dart, test/unit_tests/diff/report/json_diff_reporter_test.dart
This PR fixes the JSON report to specify "major" breaking changes in the type field in the JSON report and it adds support for omitting the version in pub refs. In that case dart_apitool will install the package without version constraints using pub and afterwards just use the latest version available in the cache.
Fixes #188 
Fixes #186
=> Report major breaking change type in JSON report and support pub refs without version

.fvmrc, lib/src/analyze/package_api_analyzer.dart
Adds a check if the "lib" folder of a package exists before iterating through the sub-tree.
Also bumps the Flutter version to 3.24.3
Fixes #195
=> Check if the "lib" directory exists before iterating its sub-tree

.github/CODEOWNERS, pubspec.yaml, scripts/ci_util/lib/src/check_lower_bound_dependencies_command.dart, scripts/ci_util/pubspec.yaml
The last two PRs had a conflict in setting the Flutter version and introducing the lower bounds check.
This PR fixes the lower bound of the analyzer package dependency and improves the ci_utils (parallel task treatment)
Also: add @marafelismino as code owner
=> improve ci utils and fix analyzer lower bound

CHANGELOG.md, lib/src/cli/commands/command_mixin.dart, pubspec.yaml, test/integration_tests/cli/extract_command_test.dart
dart_apitool has issues with packages that contain dependency_overrides in their pubspec.yaml and are pulled from pub.
Background:
Packages from pub get downloaded to the pub cache and get copied into a temporary directory to do local adaptions and preparations.
Some packages, especially ones from a mono repository, contain dependency overrides that point to relative paths. Those paths are not valid if you look at this package in isolation and pub get run on that package copy fails as it is not able to resolve those relative path overrides.
To avoid this situation dart_apitool now removed dependency overrides on that local copy (to use the variant of dependencies that would be used transitively anyways)
Fixes #198
=> fix: remove dependency_overrides from temporary pubspec.yaml

pubspec.yaml, test/integration_tests/cli/extract_command_test.dart
This PR contains the adaptations for the 0.20.1 release
=> Release 0.20.1

.fvmrc, .github/workflows/ci.yml, .vscode/settings.json, pubspec.yaml, test/integration_tests/cli/extract_command_test.dart
This PR bumps Flutter to 3.29.3 and also upgrade the lint dependencies
=> bumps Flutter version to 3.29.3

.vscode/settings.json, CHANGELOG.md, lib/src/analyze/api_relevant_elements_collector.dart, lib/src/analyze/exported_files_collector.dart, lib/src/analyze/package_api_analyzer.dart, lib/src/diff/package_api_differ.dart, lib/src/model/internal/internal_declaration_utils.dart, lib/src/model/internal/internal_executable_declaration.dart, lib/src/model/internal/internal_field_declaration.dart, lib/src/model/internal/internal_interface_declaration.dart, lib/src/model/internal/internal_type_alias_declaration.dart, lib/src/model/internal/internal_type_usage.dart, lib/src/utils/naming_utils.dart, lib/src/utils/string_utils.dart, pubspec.yaml, test/integration_tests/cli/extract_command_test.dart
This PR replaces the deprecated analyzer API calls with the newer ones.
As this caused some behavior change and adaptions that go beyond just "renaming a method call" I decided to give that change a major version bump.
=> chore: replace deprecated analyzer APIs

.fvmrc, .vscode/settings.json, README.md, lib/src/cli/commands/command_mixin.dart, lib/src/cli/commands/diff_command.dart, lib/src/cli/commands/extract_command.dart, lib/src/tooling/dart_interaction.dart, lib/src/tooling/pub_interaction.dart, test/integration_tests/cli/preparation/package_preparation_test.dart
The former approach to analyze packages (especially the ones from pub) was to copy the package content + adapt it to make `pub get` run through.
This approach has limitations and runs into all kind of issues as packages in the pub cache are not meant to be executed `pub get` directly in and certain conditions lead to failing `pub get` runs:
- example project that refers to non-existing packages from the original monorepo
- the package's dev dependencies are pointing to non-existing packages
- the package is part of a workspace
To bypass this approach completely Google employees had the idea of generating a temporary package that references the package to analyze and use that temporary package as an `pub get` and analysis entry-point.
This approach can't be used as a complete replacement …
=> Fix: run pub get indirectly

.gitignore, CHANGELOG.md, lib/src/analyze/api_relevant_elements_collector.dart, lib/src/model/type_hierarchy.dart, test/integration_tests/diff/test_package_dynamic_handling_test.dart, test/integration_tests/diff/test_package_return_type_changes_test.dart, test/test_packages/return_type_changes/package_with_narrow_returns/.gitignore, test/test_packages/return_type_changes/package_with_narrow_returns/CHANGELOG.md, test/test_packages/return_type_changes/package_with_narrow_returns/README.md, test/test_packages/return_type_changes/package_with_narrow_returns/analysis_options.yaml, test/test_packages/return_type_changes/package_with_narrow_returns/lib/package_a.dart, test/test_packages/return_type_changes/package_with_narrow_returns/lib/src/api_class.dart, test/test_packages/return_type_changes/package_with_narrow_returns/pubspec.yaml, test/test_packages/return_type_changes/package_with_wide_returns/.gitignore, test/test_packages/return_type_changes/package_with_wide_returns/CHANGELOG.md, test/test_packages/return_type_changes/package_with_wide_returns/README.md, test/test_packages/return_type_changes/package_with_wide_returns/analysis_options.yaml, test/test_packages/return_type_changes/package_with_wide_returns/lib/package_a.dart, test/test_packages/return_type_changes/package_with_wide_returns/lib/src/api_class.dart, test/test_packages/return_type_changes/package_with_wide_returns/pubspec.yaml
This PR is based on #222 
This PR fixes #221 
In this PR the TypeHierarchy that dart_apitool tracks gets extended to also understand generic types and their covariance.
This fixes return type change checks that led to breaking changes too fast (e.g. Iterable<num> -> List<int>)
=> fix: narrowing return type should not be breaking

CHANGELOG.md, README.md, lib/src/analyze/api_relevant_elements_collector.dart, lib/src/cli/cli.dart, lib/src/cli/commands/command_mixin.dart, lib/src/cli/git_ref.dart, lib/src/cli/package_ref.dart, lib/src/model/type_hierarchy.dart, lib/src/tooling/git_interaction.dart, lib/src/tooling/tooling.dart, test/integration_tests/cli/diff_command_test.dart, test/integration_tests/diff/protobuf_git_test.dart, test/integration_tests/helper/integration_test_helper.dart, test/unit_tests/cli/git_ref_test.dart
in a PR of protobuf there were some hints of weird dart_apitool behavior (https://github.com/google/protobuf.dart/pull/1026)
The main issue was that parameter type changes are detected that are none (TypeX changed to TypeX)
To investigate this issue more easily I also added git support for the package ref (solving #204 ).
And while trying get rid of all wrong changes I also fixed (parts of) https://github.com/bmw-tech/dart_apitool/issues/228 (private top level functions). I still need to check for other private types, though.
There were two major issues that are now fixed:
1. the package resolution was no longer working for package refs ('package:xxx/yyy.dart') always falling back to the "file name without extension". In the protobuf case the entry point changed from "protobuf.dart" to …
=> Fix weird protobuf changes

CHANGELOG.md, bin/main.dart, lib/src/diff/report/console_diff_reporter.dart, lib/src/utils/color_utils.dart, lib/src/utils/stdout_session.dart, lib/src/utils/utils.dart
This PR fixes issue #229 by not using color control sequences when not attached to a terminal
=> fix: don't use terminal colors when StdioType is not Terminal

CHANGELOG.md, lib/src/analyze/package_api_analyzer.dart, lib/src/model/internal/internal_executable_declaration.dart, test/integration_tests/analyze/private_types_exclusion_test.dart, test/integration_tests/analyze/typedef_handling_test.dart, test/integration_tests/diff/test_package_operators_test.dart, test/test_packages/missing_export/package_a/lib/package_a.dart, test/test_packages/missing_export/package_a/lib/types/class_c.dart, test/test_packages/missing_export/package_a/lib/types/private_types.dart
This PR solves two issues:
1. #213 entry points for typedefs were not propagated to the aliased type
2. #225 the name for unary operators was wrong
Also adds tests for #228 (but did not uncover any new issues)
=> fix: typedefs to private APIs and unary naming

.fvmrc, .vscode/settings.json, CHANGELOG.md, lib/src/analyze/api_relevant_elements_collector.dart, test/integration_tests/analyze/grpc_dart_test.dart, test/integration_tests/analyze/unexported_function_test.dart, test/test_packages/missing_export/package_a/lib/package_a.dart, test/test_packages/missing_export/package_a/lib/types/hidden_build_method.dart
dart_apitool tracks show and hide export modifiers and checks if a type is exported before adding it to the public API model. 
This works for interface types but was not implemented for:
- top level functions
- top level variables
- aliases
fixes #220 
This PR adds the check to those places as well.
Turned out that one of our integration tests actually tested that wrong behavior by accident
=> fix: hidden top level functions shall not be part of the public API

.fvmrc, .github/workflows/ci.yml, .vscode/settings.json, CHANGELOG.md, lib/src/tooling/dart_interaction.dart, pubspec.yaml, test/integration_tests/cli/extract_command_test.dart
During transfer of the package_config the root entry was added twice which led to the analyzer not being able to resolve external packages.
Also: bumps Flutter to latest stable version `3.35.2`
fixes #241
=> fix: package_config transfer
